-- =========================================================
-- Cafe QR Ordering
-- Database Schema
-- =========================================================

-- =========================================================
-- 1. Categories
-- =========================================================

create table if not exists categories (
    id bigint generated by default as identity primary key,

    name varchar(100) not null,
    slug varchar(120) not null unique,

    is_active boolean not null default true,

    sort_order integer not null default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- =========================================================
-- 2. Products
-- =========================================================

create table if not exists products (
    id bigint generated by default as identity primary key,

    category_id bigint references categories(id)
        on delete set null,

    name varchar(150) not null,

    description text,

    price integer not null
        check (price >= 0),

    available boolean not null default true,

    sort_order integer not null default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- =========================================================
-- 3. Orders
-- =========================================================

create table if not exists orders (
    id bigint generated by default as identity primary key,

    tracking_code varchar(6) not null unique,

    order_type varchar(20) not null
        check (order_type in ('dine_in', 'takeaway')),

    table_no integer,

    customer_name varchar(100),

    note text,

    status varchar(20) not null default 'new'
        check (
            status in (
                'new',
                'preparing',
                'ready',
                'done',
                'cancelled'
            )
        ),

    total integer not null default 0
        check (total >= 0),

    notify_ok boolean not null default false,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint dine_in_requires_table
        check (
            order_type = 'takeaway'
            or table_no is not null
        )
);


-- =========================================================
-- 4. Order Items
-- =========================================================

create table if not exists order_items (
    id bigint generated by default as identity primary key,

    order_id bigint not null
        references orders(id)
        on delete cascade,

    product_id bigint
        references products(id)
        on delete set null,

    product_name varchar(150) not null,

    quantity integer not null
        check (quantity > 0),

    unit_price integer not null
        check (unit_price >= 0),

    subtotal integer not null
        check (subtotal >= 0),

    created_at timestamptz not null default now()
);


-- =========================================================
-- 5. Reviews
-- =========================================================

create table if not exists reviews (
    id bigint generated by default as identity primary key,

    order_id bigint not null unique
        references orders(id)
        on delete cascade,

    rating integer not null
        check (rating between 1 and 5),

    comment text,

    created_at timestamptz not null default now()
);


-- =========================================================
-- Indexes
-- =========================================================

create index if not exists idx_products_category
    on products(category_id);

create index if not exists idx_products_available
    on products(available);

create index if not exists idx_orders_status
    on orders(status);

create index if not exists idx_orders_created_at
    on orders(created_at desc);

create index if not exists idx_orders_tracking_code
    on orders(tracking_code);

create index if not exists idx_order_items_order
    on order_items(order_id);

create index if not exists idx_reviews_created_at
    on reviews(created_at desc);


-- =========================================================
-- Row Level Security
-- =========================================================

alter table categories enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table reviews enable row level security;









-- ================================
-- Admins
-- ================================

create table if not exists admins (
    id bigint generated by default as identity primary key,

    email varchar(255) not null unique,

    password_hash text not null,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


create index if not exists idx_admins_email
    on admins(email);


create index if not exists idx_admins_is_active
    on admins(is_active);


alter table admins enable row level security;